enableTelemetry: false

nodeLinker: node-modules

npmPublishAccess: public

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-pin-deps.cjs
    spec: "https://raw.githubusercontent.com/splitgraph/yarn-plugin-pin-deps/main/packages/plugin-pin-deps/bundles/%40yarnpkg/plugin-pin-deps.js"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.1.cjs

packageExtensions:
  # Suppress false alarm peerDependency warnings from packages that omit `typescript`
  # from `devDependencies`, since we know root package always provides `typescript`
  ts-node@*:
    peerDependenciesMeta:
      typescript:
        optional: true
