enableTelemetry: false

nodeLinker: node-modules

npmPublishAccess: private

# npmScopes:
#   madatdata:
#     npmPublishRegistry: '${VERDACCIO:-"https://registry.yarnpkg.com"}'
#     npmRegistryServer: '${VERDACCIO:-"https://registry.yarnpkg.com"}'

unsafeHttpWhitelist:
  - localhost

yarnPath: .yarn/releases/yarn-3.2.1.cjs
