name: Build and test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # NOTE: fetch-depth of 0 means "fetch all history and tags"
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install --immutable
      - run: yarn format.check
      - run: yarn build
      # NOTE: misleading. test doesn't actually depend on build.
      - run: yarn test-ci
